2023-07-19 03:45:58,846 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2023-07-19 03:45:58,848 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2023-07-19 03:45:58,848 DEBUG    root            Running [gcloud.projects.describe] with arguments: [--account: "ron.mcclain@figure-eight.com", --configuration: "default", --format: "value(name)", PROJECT_ID_OR_NUMBER: "devspace-256022"]
2023-07-19 03:46:12,126 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-07-19 03:46:12,127 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/devspace-256022?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11202d910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-19 03:46:12,127 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/devspace-256022?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/devspace-256022?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11202d910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-19 03:46:14,140 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-07-19 03:46:14,142 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/devspace-256022?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111f40b10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-19 03:46:14,142 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/devspace-256022?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/devspace-256022?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111f40b10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-19 03:46:18,106 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-07-19 03:46:18,109 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/devspace-256022?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111f22890>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-19 03:46:18,109 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/devspace-256022?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/devspace-256022?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111f22890>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-19 03:46:27,848 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-07-19 03:46:57,854 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/devspace-256022?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11209f250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-19 03:46:57,855 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/devspace-256022?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/devspace-256022?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11209f250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-07-19 03:47:15,839 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
